service: serverless-zork-clone
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  map:
    handler: ./src/handler.map
    events:
      - httpApi:
          path: /map
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    reloadHandler: true